site_name: "RSpec-specific analysis for your projects, as an extension to RuboCop."
repo_url: https://github.com/rubocop-rspec/rubocop-rspec
docs_dir: manual
pages:
- Home: index.md
- Installation: installation.md
- Usage: usage.md
- Cops: cops.md
- Cops Documentation:
    - RSpec Cops: cops_rspec.md
    - Rails Cops: cops_rails.md
    - FactoryBot Cops: cops_factorybot.md
    - Capybara Cops: cops_capybara.md
theme: readthedocs
