#
# Configuration of obsolete/deprecated cops used by `ConfigObsoletion`.
#
# See: https://docs.rubocop.org/rubocop/extensions.html#config-obsoletions
#

# Cop parameters that have been changed
# Can be treated as a warning instead of a failure with `severity: warning`
changed_parameters:
  - cops:
      - RSpec/VariableName
    parameters: IgnoredPatterns
    alternative: AllowedPatterns
    severity: warning

renamed:
  RSpec/Capybara/CurrentPathExpectation: Capybara/CurrentPathExpectation
  RSpec/Capybara/MatchStyle: Capybara/MatchStyle
  RSpec/Capybara/NegationMatcher: Capybara/NegationMatcher
  RSpec/Capybara/SpecificActions: Capybara/SpecificActions
  RSpec/Capybara/SpecificFinders: Capybara/SpecificFinders
  RSpec/Capybara/SpecificMatcher: Capybara/SpecificMatcher
  RSpec/Capybara/VisibilityMatcher: Capybara/VisibilityMatcher
